r"""Emit paper1/table1.tex -- the operating-point table that replaced the Fig. 3 plot.

Kian rejected the rate-vs-switching scatter: the frontier is flat, so a plot spends
a quarter page saying "these numbers are close together" when the numbers themselves
say it in one line. A table also lets the pilot budget and the switching weight sit
in the same object, which the two-figure version could not do.

Two data sources, both at OP_V3 (N=441, M=10, K=3, n_rf=6, AR(4), f_D T_s = 0.1):

  results_tm/fig2_pilot_sweep.json  m sweep at eta_sw = 1   (15 seeds, canonical)
  results_tm/fig2_table.json        same sweep, but records SWITCHING too (8 seeds)
  results_tm/fig3_frontier.json     eta_sw sweep at m = 6   (8 seeds)

The rate column comes from the 15-seed file because it is the one the figure is
built from and it has the tighter error bars; the switching and objective columns
for those rows come from fig2_table.json, which is the same configuration re-run
with switch counts recorded. If that file is missing the cells print as "--" so the
paper still builds while the run is in flight.

PILOT DENOMINATORS. Two of them, and conflating them is the thing most likely to
mislead a reader. m/M is the fraction of ACTIVATED ports that are piloted; m/N is
the fraction of the whole candidate grid that is ever measured. m = M = 10 is
"every activated port piloted" -- it is NOT full CSI, it is 2.3% of the array.

Run:  python make_table1.py
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "results_tm"
OUT = Path(__file__).resolve().parent / "table1.tex"

N_PORTS, M_ACT, ETA_REF = 441, 10, 1.0


def load(name):
    p = RES / name
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None


def cell(x, fmt="{:.2f}"):
    return "--" if x is None else fmt.format(x)


def main() -> int:
    d2 = load("fig2_pilot_sweep.json")          # rates, 15 seeds
    d2s = load("fig2_table.json")               # rates + switches, 8 seeds
    d3 = load("fig3_frontier.json")             # eta sweep at m = 6

    src = d2s if d2s else d2                    # prefer the run that has switching
    genie = float(np.mean(src["genie"]))
    # genie switching is only recorded by the newer runs
    gsw = None
    for d in (d2s, d3):
        if d and d.get("genie_switch"):
            gsw = float(np.mean(d["genie_switch"]))
            break

    m_list = [int(m) for m in src["meta"]["m_list"]]
    rows_m = []
    for m in m_list:
        v = src["rates"][str(m)]
        r = float(np.mean(v))
        se = float(np.std(v, ddof=1) / np.sqrt(len(v)))
        w = float(np.mean(src["switch"][str(m)])) if str(m) in src.get("switch", {}) else None
        rows_m.append((m, r, se, w, None if w is None else r - ETA_REF * w))

    # eta = 8 is bit-identical to eta = 4 (the array is already frozen); one row
    # of the saturated regime is the result, two is padding.
    etas = [e for e in (0.0, 1.0, 4.0) if str(e) in d3["rate"]]
    rows_e = []
    for e in etas:
        r = float(np.mean(d3["rate"][str(e)]))
        w = float(np.mean(d3["switch"][str(e)]))
        rows_e.append((e, r, w, r - ETA_REF * w))

    L = []
    A = L.append
    A(r"% GENERATED BY make_table1.py -- do not edit by hand, edit the script.")
    A(r"\begin{table}[t]")
    A(r"\centering")
    A(r"\caption{Operating points; conditions as in "
      r"Section~\ref{sec:results}-A, objective \eqref{eq:problem} at "
      r"$\eta_{\mathrm{sw}}=1$. $m/M$ is the piloted fraction of the "
      r"\textup{activated} ports, $m/N$ of the whole grid: even $m=M$ is "
      r"partial CSI.}")
    A(r"\label{tab:ops}")
    A(r"\renewcommand{\arraystretch}{1.02}")
    A(r"\setlength{\tabcolsep}{3.2pt}")
    A(r"\footnotesize")
    A(r"\begin{tabular}{@{}ccccrrrr@{}}")
    A(r"\hline\hline")
    A(r"$m$ & $\eta_{\mathrm{sw}}$ & $m/M$ & $m/N$ & Sw./slot & Rate & \% genie & Obj. \\")
    A(r" & & (\%) & (\%) & & (b/s/Hz) & & (b/s/Hz) \\")
    A(r"\hline")
    A(r"\multicolumn{8}{@{}l}{\emph{(a) pilot budget, at "
      r"$\eta_{\mathrm{sw}}=1$}}\\")
    for m, r, se, w, o in rows_m:
        star = r"\,$^\dagger$" if m == 6 else (r"\,$^\ddagger$" if m == M_ACT else "")
        A(f"{m}{star} & $1$ & {100*m/M_ACT:.0f} & {100*m/N_PORTS:.2f} & "
          f"{cell(w)} & {r:.2f} & {100*r/genie:.1f} & {cell(o)} \\\\")
    A(r"\hline")
    A(r"\multicolumn{8}{@{}l}{\emph{(b) switching weight, at $m=6$}}\\")
    for e, r, w, o in rows_e:
        A(f"$6$ & ${e:g}$ & $60$ & $1.36$ & {w:.2f} & {r:.2f} & "
          f"{100*r/genie:.1f} & {o:.2f} \\\\")
    A(r"\hline")
    A(r"\multicolumn{4}{@{}l}{Full-CSI genie} & "
      f"{cell(gsw)} & {genie:.2f} & 100.0 & {cell(None if gsw is None else genie-gsw)} "
      r"\\")
    A(r"\hline\hline")
    A(r"\end{tabular}")
    A(r"\vspace{2pt}")
    A(r"\begin{flushleft}\footnotesize $^\dagger$ operating point used throughout; "
      r"$^\ddagger$ every activated port piloted.\end{flushleft}")
    A(r"\end{table}")

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")
    print(f"  genie {genie:.3f} b/s/Hz" + (f", {gsw:.2f} sw/slot" if gsw else ", switching PENDING"))
    print(f"  block (a): {len(rows_m)} rows, switching "
          f"{'recorded' if rows_m[0][3] is not None else 'PENDING (fig2_table.json)'}")
    print(f"  block (b): {len(rows_e)} rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
